name: Sync Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.FORKED_REPO_TOKEN }}
        ref: main

    - name: Sync
      run: |
        git remote add upstream https://github.com/0-ROK/zzm-web.git
        git push upstream main
