name: Push Commits

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.FORKED_REPO_TOKEN }}
        ref: main

    - name: Push
      run: |
        git remote add target https://github.com/0-ROK/zzm-web.git
        git push target main:main
