name: Sync Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
    - name: Sync
      run: |
        git remote add upstream https://github.com/0-ROK/zzm-web.git
        git fetch upstream
        git merge upstream/main
        git push
